apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hb1jv9isa-python
  janus-idp.io/tekton: hb1jv9isa-python
  backstage.io/kubernetes-id: hb1jv9isa-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hb1jv9isa-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
