apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hb1jv9isa-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hb1jv9isa-python 
  name: hb1jv9isa-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: hb1jv9isa-python 
